# Generated by Django 3.1.2 on 2020-11-25 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=100)),
                ('transporter', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('etd', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
